// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// modules
export const FETCH_MODULES = 'FETCH_USER'
export const FETCH_MODULES_SUCCESS = 'FETCH_MODULES_SUCCESS'
export const FETCH_MODULES_FAILURE = 'FETCH_MODULES_FAILURE'
export const GET_MODULE_SUCCESS = 'GET_MODULE_SUCCESS'
export const GET_MODULE_FAILURE = 'GET_MODULE_FAILURE'

// lessons
export const FETCH_LESSONS = 'FETCH_LESSONS'
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS'
export const FETCH_LESSONS_FAILURE = 'FETCH_LESSONS_FAILURE'
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS'
export const GET_LESSON_FAILURE = 'GET_LESSON_FAILURE'

