// auth.js
export const LOGOUT = 'LOGOUT'
export const SAVE_TOKEN = 'SAVE_TOKEN'
export const FETCH_USER = 'FETCH_USER'
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS'
export const FETCH_USER_FAILURE = 'FETCH_USER_FAILURE'
export const UPDATE_USER = 'UPDATE_USER'

// lang.js
export const SET_LOCALE = 'SET_LOCALE'

// modules
export const FETCH_MODULES = 'FETCH_USER'
export const FETCH_MODULES_SUCCESS = 'FETCH_MODULES_SUCCESS'
export const FETCH_MODULES_FAILURE = 'FETCH_MODULES_FAILURE'
export const GET_MODULE_SUCCESS = 'GET_MODULE_SUCCESS'
export const GET_MODULE_FAILURE = 'GET_MODULE_FAILURE'

// lessons
export const FETCH_LESSONS = 'FETCH_LESSONS'
export const FETCH_LESSONS_SUCCESS = 'FETCH_LESSONS_SUCCESS'
export const FETCH_LESSONS_FAILURE = 'FETCH_LESSONS_FAILURE'
export const GET_LESSON_SUCCESS = 'GET_LESSON_SUCCESS'
export const GET_LESSON_FAILURE = 'GET_LESSON_FAILURE'


// review drills
export const FETCH_DRILLS = 'FETCHDRILLS'
export const FETCH_DRILLS_SUCCESS = 'FETCH_DRILLS_SUCCESS'
export const FETCH_DRILLS_FAILURE = 'FETCH_DRILLS_FAILURE'
export const GET_DRILL_SUCCESS = 'GET_DRILL_SUCCESS'
export const GET_DRILL_FAILURE = 'GET_DRILL_FAILURE'


// review ebooks
export const FETCH_EBOOKS = 'FETCH_EBOOKS'
export const FETCH_EBOOKS_SUCCESS = 'FETCH_EBOOKS_SUCCESS'
export const FETCH_EBOOKS_FAILURE = 'FETCH_EBOOKS_FAILURE'
export const GET_EBOOK_SUCCESS = 'GET_EBOOK_SUCCESS'
export const GET_EBOOK_FAILURE = 'GET_EBOOK_FAILURE'


// review materials
export const FETCH_REVIEW_MATERIALS = 'FETCH_REVIEW_MATERIALS'
export const FETCH_REVIEW_MATERIALS_SUCCESS = 'FETCH_REVIEW_MATERIALS_SUCCESS'
export const FETCH_REVIEW_MATERIALS_FAILURE = 'FETCH_REVIEW_MATERIALS_FAILURE'
export const GET_REVIEW_MATERIAL_SUCCESS = 'GET_REVIEW_MATERIAL_SUCCESS'
export const GET_REVIEW_MATERIAL_FAILURE = 'GET_REVIEW_MATERIAL_FAILURE'

// user tests
export const FETCH_USER_TESTS_SUCCESS = 'FETCH_USER_TESTS_SUCCESS'
export const FETCH_USER_TESTS_FAILURE = 'FETCH_USER_TESTS_FAILURE'
export const FINISH_USER_TESTS_SUCCESS = 'FINISH_USER_TESTS_SUCCESS'
export const FINISH_USER_TESTS_FAILURE = 'FINISH_USER_TESTS_FAILURE'

// tests
export const GET_TEST_SUCCESS = 'GET_TEST_SUCCESS'
export const GET_TEST_FAILURE = 'GET_TEST_FAILURE'

// questions
export const FETCH_QUESTIONS_SUCCESS = 'FETCH_QUESTIONS_SUCCESS'
export const FETCH_QUESTIONS_FAILURE = 'FETCH_QUESTIONS_FAILURE'

// choices
export const FETCH_CHOICES_SUCCESS = 'FETCH_CHOICES_SUCCESS'
export const FETCH_CHOICES_FAILURE = 'FETCH_CHOICES_FAILURE'

// student answers
export const FETCH_STUDENT_ANSWERS_SUCCESS = 'FETCH_STUDENT_ANSWERS_SUCCESS'
export const FETCH_STUDENT_ANSWERS_FAILURE = 'FETCH_STUDENT_ANSWERS_FAILURE'
