export const ROUTE_NAMES = {
  HOME: 'home',
  LOGIN: 'login',
  WELCOME: 'welcome',
  PASSWORD_REQUEST: 'password.request',
  PASSWORD_RESET: 'password.reset',
  DASHBOARD: 'dashboard',
  SETTINGS: 'settings',
  SETTINGS_PROFILE: 'settings.profile',
  SETTINGS_PASSWORD: 'settings.password',
  MODULES: 'modules',
  LESSONS: 'lessons',
  LESSONS_OPTIONS: 'lesson.options',
  REVIEW_MATERIALS: 'review_materials',
  REVIEW_MATERIAL: 'review_material',
  PRETEST: 'pretest',
  POSTTEST: 'posttest',
  PERIODICALTEST: 'periodicaltest',
  DRILLS: 'drills',
  DRILL: 'drill',
  EBOOK: 'ebook',
  CONTACT: 'contact',
  CORE_VALUES: 'core_values',
  MISSION: 'mission',
  VISION: 'vision',
  HISTORY: 'history'
}
