export const ROUTE_NAMES = {
  HOME: 'home',
  LOGIN: 'login',
  WELCOME: 'welcome',
  PASSWORD_REQUEST: 'password.request',
  PASSWORD_RESET: 'password.reset',
  DASHBOARD: 'dashboard',
  SETTINGS: 'settings',
  SETTINGS_PROFILE: 'settings.profile',
  SETTINGS_PASSWORD: 'settings.password',
  MODULES: 'modules',
  LESSONS: 'lessons',
  LESSONS_OPTIONS: 'lesson.options',
  REVIEW_MATERIALS: 'review_materials',
  REVIEW_MATERIAL: 'review_material',
  PRETESTS: 'pretests',
  PRETEST: 'pretest',
  POSTTESTS: 'posttests',
  POSTTEST: 'posttest',
  DRILLS: 'drills',
  DRILL: 'drill'
}
