export const ROUTE_NAMES = {
  HOME: 'home',
  LOGIN: 'login',
  WELCOME: 'welcome',
  PASSWORD_REQUEST: 'password.request',
  PASSWORD_RESET: 'password.reset',
  DASHBOARD: 'dashboard',
  SETTINGS: 'settings',
  SETTINGS_PROFILE: 'settings.profile',
  SETTINGS_PASSWORD: 'settings.password',
  MODULES: 'modules',
  LESSONS: 'lessons',
  LESSONS_OPTIONS: 'lesson.options',
  REVIEW_MATERIALS: 'review_materials',
  REVIEW_MATERIAL: 'review_material',
  PRE_TESTS: 'pre_tests',
  PRE_TEST: 'pre_test',
  POST_TESTS: 'post_tests',
  POST_TEST: 'post_test',
  DRILLS: 'drills',
  DRILL: 'drill',
}
